import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F9FAFB" },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    paddingVertical: 14,
    minHeight: 56,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  iconBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  topTitle: { fontSize: 16, fontWeight: "700", color: "#111827" },
  scroll: { padding: 16, paddingBottom: 24 },
  previewWrap: {
    position: "relative",
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#000",
  },
  preview: { width: "100%", height: 200, resizeMode: "contain" },
  retakeBtn: {
    position: "absolute",
    bottom: 10,
    right: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(17,24,39,0.85)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  retakeText: { color: "#FFFFFF", fontSize: 11, fontWeight: "700" },
  aiNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#EEF2FF",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    marginTop: 14,
  },
  aiBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#7C3AED",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  aiBadgeText: { color: "#FFFFFF", fontSize: 10, fontWeight: "700" },
  aiNoticeText: { color: "#3730A3", fontSize: 11, lineHeight: 16, flex: 1 },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    marginTop: 12,
  },
  cardLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 12,
  },
  cardLabelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  fieldLabel: {
    fontSize: 11,
    color: "#6B7280",
    fontWeight: "600",
    marginBottom: 6,
  },
  input: {
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: "#111827",
  },
  readonlyRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  readonlyText: { color: "#374151", fontSize: 13 },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#F3F4F6",
    borderWidth: 1,
    borderColor: "transparent",
  },
  chipActive: {
    backgroundColor: "#EFF6FF",
    borderColor: "#3B82F6",
  },
  chipText: { color: "#6B7280", fontSize: 12, fontWeight: "600" },
  chipTextActive: { color: "#3B82F6", fontWeight: "700" },
  catChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  catChipText: { color: "#6B7280", fontSize: 12, fontWeight: "600" },
  aiDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#7C3AED",
    marginLeft: 2,
  },
  confPill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  confPillText: { fontSize: 10, fontWeight: "700" },
  feedbackBox: {
    flexDirection: "row",
    gap: 6,
    backgroundColor: "#F5F3FF",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    marginTop: 10,
    alignItems: "center",
  },
  feedbackText: { color: "#6D28D9", fontSize: 11, flex: 1, lineHeight: 16 },
  itemRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    marginBottom: 8,
  },
  itemNameInput: { flex: 1 },
  itemPriceInput: { width: 100, textAlign: "right" },
  removeBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#FEF2F2",
    alignItems: "center",
    justifyContent: "center",
  },
  addItemBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "#EFF6FF",
    marginTop: 4,
  },
  addItemText: { color: "#3B82F6", fontWeight: "700", fontSize: 12 },
  tinyBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "#EFF6FF",
  },
  tinyBtnText: { color: "#3B82F6", fontSize: 11, fontWeight: "700" },
  totalCard: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 18,
  },
  totalLabel: { color: "#6B7280", fontWeight: "600", fontSize: 13 },
  totalInput: {
    flex: 1,
    marginLeft: 12,
    fontSize: 22,
    fontWeight: "800",
    color: "#111827",
    textAlign: "right",
  },
  totalSuffix: {
    color: "#111827",
    fontWeight: "700",
    fontSize: 16,
    marginLeft: 4,
  },
  memoInput: { minHeight: 60, textAlignVertical: "top" },
  rawToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    alignSelf: "center",
    paddingVertical: 12,
  },
  rawToggleText: { color: "#6B7280", fontSize: 12 },
  rawBox: {
    backgroundColor: "#111827",
    borderRadius: 12,
    padding: 14,
  },
  rawText: { color: "#D1D5DB", fontSize: 11, lineHeight: 18, fontFamily: Platform.select({ ios: "Menlo", default: "monospace" }) },
  bottomBar: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
  },
  saveBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#3B82F6",
    paddingVertical: 14,
    borderRadius: 14,
  },
  saveBtnText: { color: "#FFFFFF", fontWeight: "800", fontSize: 15 },
  /* empty */
  emptyTitle: { fontSize: 22, fontWeight: "800", color: "#111827", marginTop: 8 },
  emptySub: {
    color: "#6B7280",
    fontSize: 13,
    lineHeight: 20,
    marginTop: 8,
  },
  featureRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 24,
    marginBottom: 24,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#F3F4F6",
  },
  featureItem: { alignItems: "center", flex: 1 },
  featureIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
  },
  featureLabel: { color: "#374151", fontSize: 12, fontWeight: "600" },
  bigPrimary: {
    flexDirection: "row",
    gap: 10,
    backgroundColor: "#3B82F6",
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  bigPrimaryText: { color: "#FFFFFF", fontWeight: "800", fontSize: 15 },
  bigSecondary: {
    flexDirection: "row",
    gap: 10,
    backgroundColor: "#EFF6FF",
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  bigSecondaryText: { color: "#2563EB", fontWeight: "800", fontSize: 15 },
  tipBox: {
    flexDirection: "row",
    gap: 8,
    alignItems: "flex-start",
    backgroundColor: "#F3F4F6",
    padding: 12,
    borderRadius: 12,
    marginTop: 16,
  },
  tipBoxText: { color: "#6B7280", fontSize: 12, lineHeight: 18, flex: 1 },
  /* analyzing */
  analyzePreviewWrap: {
    width: "70%",
    aspectRatio: 0.75,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "#000",
    position: "relative",
    marginTop: 8,
  },
  analyzePreview: { width: "100%", height: "100%", resizeMode: "cover" },
  scanlineOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(59,130,246,0.25)",
    alignItems: "center",
    justifyContent: "center",
  },
  analyzeHeading: {
    marginTop: 20,
    fontSize: 17,
    fontWeight: "700",
    color: "#111827",
  },
  stepList: { width: "100%", marginTop: 20, gap: 12 },
  stepRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  stepBadge: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  stepBadgeNum: { color: "#9CA3AF", fontSize: 12, fontWeight: "700" },
  stepLabel: { color: "#9CA3AF", fontSize: 14 },

  /* 직접 입력 모드 안내 */
  infoNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#EFF6FF",
    borderWidth: 1,
    borderColor: "#BFDBFE",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    marginTop: 10,
  },
  infoText: { color: "#1D4ED8", fontSize: 11, lineHeight: 16, flex: 1 },

  /* OCR 결과 부실 안내 */
  warnNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FFFBEB",
    borderWidth: 1,
    borderColor: "#FDE68A",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    marginTop: 10,
  },
  warnText: { color: "#B45309", fontSize: 11, lineHeight: 16, flex: 1 },

  /* 텍스트 붙여넣기 진입 */
  bigGhost: {
    flexDirection: "row",
    gap: 10,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFFFFF",
  },
  bigGhostText: { color: "#374151", fontWeight: "700", fontSize: 14 },

  /* 텍스트 붙여넣기 모달 */
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 32,
  },
  modalHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalTitle: { fontSize: 16, fontWeight: "800", color: "#111827" },
  modalSub: {
    color: "#6B7280",
    fontSize: 12,
    marginTop: 6,
    lineHeight: 17,
  },
  modalInput: {
    marginTop: 14,
    minHeight: 180,
    maxHeight: 260,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    padding: 12,
    fontSize: 13,
    color: "#111827",
    backgroundColor: "#F9FAFB",
    fontFamily: Platform.select({ ios: "Menlo", default: "monospace" }),
  },
  modalConfirm: {
    flexDirection: "row",
    gap: 8,
    marginTop: 14,
    backgroundColor: "#3B82F6",
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  modalConfirmText: { color: "#FFFFFF", fontWeight: "800", fontSize: 14 },
});
