import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#FFFFFF" },
  container: {
    flex: 1,
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingTop: 72,
    paddingBottom: 28,
  },
  hero: { alignItems: "center" },
  logo: {
    width: 76,
    height: 76,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EFF6FF",
    marginBottom: 24,
  },
  title: { fontSize: 30, fontWeight: "800", color: "#111827", letterSpacing: -0.8 },
  subtitle: {
    marginTop: 12,
    color: "#6B7280",
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
  },
  featureList: { marginTop: 44, width: "100%", gap: 18 },
  feature: { flexDirection: "row", alignItems: "center", gap: 12 },
  featureIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F3F4F6",
  },
  featureText: { color: "#374151", fontSize: 14, fontWeight: "600" },
  loginButton: {
    height: 56,
    borderRadius: 14,
    backgroundColor: "#FEE500",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  loginButtonPressed: { opacity: 0.78 },
  loginButtonDisabled: { opacity: 0.55 },
  loginText: { color: "#191919", fontSize: 16, fontWeight: "700" },
  notice: { marginTop: 14, color: "#9CA3AF", fontSize: 11, lineHeight: 16, textAlign: "center" },
});
