import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F9FAFB" },
  header: {
    height: 56,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E5E7EB",
    backgroundColor: "#FFFFFF",
  },
  headerButton: { width: 40, height: 40, alignItems: "center", justifyContent: "center" },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    color: "#111827",
    fontSize: 18,
    fontWeight: "700",
  },
  headerSpacer: { width: 40 },
  content: { flexGrow: 1, padding: 20 },
  profileCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    padding: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    backgroundColor: "#FFFFFF",
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EFF6FF",
  },
  profileText: { flex: 1 },
  profileName: { color: "#111827", fontSize: 18, fontWeight: "800" },
  loginMethod: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 6,
    marginTop: 8,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "#FEE500",
  },
  loginMethodText: { color: "#4A4000", fontSize: 11, fontWeight: "700" },
  section: { marginTop: 28 },
  sectionTitle: { marginBottom: 10, color: "#6B7280", fontSize: 13, fontWeight: "700" },
  budgetCard: {
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    backgroundColor: "#FFFFFF",
  },
  budgetHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  budgetIcon: {
    width: 38,
    height: 38,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EFF6FF",
  },
  budgetCopy: { flex: 1 },
  budgetLabel: { color: "#6B7280", fontSize: 12, fontWeight: "600" },
  budgetValue: { color: "#111827", fontSize: 18, fontWeight: "800", marginTop: 2 },
  budgetEditButton: {
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#EFF6FF",
  },
  budgetEditText: { color: "#2563EB", fontSize: 12, fontWeight: "700" },
  budgetEditor: { marginTop: 14, paddingTop: 14, borderTopWidth: 1, borderTopColor: "#F3F4F6" },
  budgetInputRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 12,
    backgroundColor: "#F9FAFB",
  },
  budgetInput: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 11,
    color: "#111827",
    fontSize: 18,
    fontWeight: "800",
    textAlign: "right",
  },
  budgetUnit: { paddingRight: 12, color: "#6B7280", fontSize: 14, fontWeight: "600" },
  budgetPreview: { marginTop: 6, color: "#3B82F6", fontSize: 12, fontWeight: "700", textAlign: "right" },
  budgetActions: { flexDirection: "row", justifyContent: "flex-end", gap: 8, marginTop: 12 },
  budgetCancelButton: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 10, backgroundColor: "#F3F4F6" },
  budgetCancelText: { color: "#4B5563", fontSize: 13, fontWeight: "700" },
  budgetSaveButton: { minWidth: 70, paddingHorizontal: 16, paddingVertical: 10, alignItems: "center", borderRadius: 10, backgroundColor: "#2563EB" },
  budgetSaveText: { color: "#FFFFFF", fontSize: 13, fontWeight: "700" },
  menuRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    minHeight: 60,
    paddingHorizontal: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    backgroundColor: "#FFFFFF",
  },
  menuRowPressed: { backgroundColor: "#FEF2F2" },
  menuRowDisabled: { opacity: 0.55 },
  logoutRow: { marginTop: 10 },
  categoryIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EFF6FF",
  },
  menuText: { flex: 1, color: "#111827", fontSize: 15, fontWeight: "700" },
  logoutIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FEF2F2",
  },
  logoutText: { flex: 1, color: "#EF4444", fontSize: 15, fontWeight: "700" },
  version: { marginTop: "auto", textAlign: "center", color: "#9CA3AF", fontSize: 12 },
});
